repos:
    - repo: local
      hooks:
        - id: format_code
          name: format_code
          entry: python3 hooks/format_code.py
          language: system
          always_run: true
          pass_filenames: true
          types: ['c++']
          stages: [commit]
        - id: conventional_commits
          name: conventional_commits
          entry: python3 hooks/conventional_commits.py
          language: system
          always_run: true
          stages: [commit-msg]
